### ISSUE TITLE
Write GitHub Action workflow to verify template works

### ISSUE THREAD

**Issue by ipmb** [lincolnloop/django-layout#15]
Requirements:

* set to run on the main branch once per week and on any push
* steps would be something like:
  * setup Python
  * run 
      ```bash
      pip install django
      django-admin.py startproject --template=https://github.com/lincolnloop/django-layout/zipball/main --extension=py,rst,gitignore,cfg,in,yml,json,dockerignore --name=Makefile,Dockerfile testproj
      ```
  * in the `testproj` directory, start the services and wait for django migrations to finish (things should be up-and-running by then)
      ```bash
      docker compose up -d
      docker attach $(docker compose ps -q django-migrate)
      ```
  * verify you can connect to the site: (I think you get a 200 status code on a new project setup?)
      ```bash
      curl -I --retry 10 --retry-connrefused --fail localhost:8000
      ````
  * verify all the services are running
     ```bash
     docker ps  # show service status for debugging
     test $(docker ps -q | wc -l) = "2"
     ```

**Comment by ipmb** [comment]
Here's a start:

```yaml
name: test

on:
  schedule:
    - cron:  '0 5 0 * *'
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12' 
      - name: create project
        run: |
          pip install django
          django-admin startproject --template=https://github.com/lincolnloop/django-layout/zipball/master --extension=py,rst,gitignore,cfg,in,yml,json,dockerignore --name=Makefile,Dockerfile testproj
      - name: start services
        run: |
          docker compose up -d
          docker attach $(docker compose ps -q django-migrate)
        working-directory: testproj
     # ...
```
