### ISSUE TITLE
Move everything to pyproject.toml

### ISSUE THREAD

**Issue by ipmb** [lincolnloop/django-layout#19]
All these can go away:

* `setup.cfg`
* `setup.py`
* requirements/*`

Here are some snippets for `pyproject.toml` that can be adapted:

```toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "{{ project_name }}"
version = "4.0"
dependencies = [
  "django==4.2.*",
  ...
]


[project.optional-dependencies]
dev = [
  "django-stubs",
  "mypy",
  "pip-tools",
  "readable-log-formatter",
  "ruff",
]

[tool.setuptools]
packages = { "find" = { } }
include-package-data = true
```

...and this is a script that can be added to do generate the lockfiles from `pyproject.toml`:

```bash
#!/bin/bash
# Intended to run in a docker container. Called by `make requirements.txt`
set -euf -o pipefail

pip install --disable-pip-version-check --root-user-action=ignore -U pip pip-tools
# Compile main requirements
pip-compile -v \
  --resolver=backtracking \
  --generate-hashes \
  --strip-extras \
  --output-file=requirements.txt \
  pyproject.toml

# Compile dev requirements
pip-compile -v \
  --constraint $(pwd)/requirements.txt \
  --resolver=backtracking \
  --generate-hashes \
  --extra=dev \
  --output-file=requirements-dev.txt \
  pyproject.toml
  ```
